[env]
build_unflags = -std=gnu++11
build_flags = -std=c++2a -Os -fuse-ld=gold

monitor_speed = 115200

board_build.partitions = min_spiffs.csv
monitor_filters = esp32_exception_decoder

lib_deps =
	adafruit/Adafruit NeoPixel@^1.11.0
	tirus/LedControlAndAnimation@^1.4.4
	tirus/BLE Remote@^0.6.3

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

build_flags = ${env.build_flags} -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
